; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Mage Watch"
#define MyAppVersion "1.1.0"
#define MyAppPublisher "FJMM"
#define MyAppURL "https://www.example.com/"
#define MyAppExeName "TowerDefense.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E41661B2-45E8-4D34-A984-5339BC16A4AA}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\jlrdv\OneDrive\Área de Trabalho
OutputBaseFilename=Instalador Mage Watch
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\jlrdv\OneDrive\Documentos\Jogo AED1\TowerDefense\build\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\jlrdv\OneDrive\Documentos\Jogo AED1\TowerDefense\Assets\*"; DestDir: "{app}\Assets"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\jlrdv\OneDrive\Documentos\Jogo AED1\TowerDefense\build\Release\openal32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\jlrdv\OneDrive\Documentos\Jogo AED1\TowerDefense\build\Release\sfml-audio-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\jlrdv\OneDrive\Documentos\Jogo AED1\TowerDefense\build\Release\sfml-audio-d-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\jlrdv\OneDrive\Documentos\Jogo AED1\TowerDefense\build\Release\sfml-graphics-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\jlrdv\OneDrive\Documentos\Jogo AED1\TowerDefense\build\Release\sfml-graphics-d-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\jlrdv\OneDrive\Documentos\Jogo AED1\TowerDefense\build\Release\sfml-network-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\jlrdv\OneDrive\Documentos\Jogo AED1\TowerDefense\build\Release\sfml-network-d-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\jlrdv\OneDrive\Documentos\Jogo AED1\TowerDefense\build\Release\sfml-system-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\jlrdv\OneDrive\Documentos\Jogo AED1\TowerDefense\build\Release\sfml-system-d-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\jlrdv\OneDrive\Documentos\Jogo AED1\TowerDefense\build\Release\sfml-window-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\jlrdv\OneDrive\Documentos\Jogo AED1\TowerDefense\build\Release\sfml-window-d-2.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

